[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "export npm_config_cache=/tmp/.npm-cache",
  "export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true",
  "npm ci --prefer-offline --no-audit --legacy-peer-deps"
]

[start]
cmd = "npm start"

